language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer -n --prefer-source install

script:
  - bin/phpunit
  - bin/behat --format progress
  - bin/phpstan analyse -l max -c phpstan.neon src/
  - bin/phpcs
  - bin/infection
